### ISSUE TITLE
Access filesystem so many

### ISSUE THREAD

**Issue by knightXun** [thedevsaddam/snapshot#1]
i notice this k-v access filesystem so many.So how is this system profermance?

**Comment by thedevsaddam** [comment]
It uses the file system to persist data, though I have a plan to load data into memory so that it can be accessed faster. If you are interested you can send a PR. Note I don't recommend you to use this where you need huge performance. There are some good tools for these. I have built it for test purposes. Btw here is a benchmark result in my MBP 2015 i5, 8GB

|                                 	|         	|              	|            	|               	|
|---------------------------------	|---------	|--------------	|------------	|---------------	|
| BenchmarkCollection_Put-4       	| 10000   	| 225331 ns/op 	| 1416 B/op  	| 33 allocs/op  	|
| BenchmarkCollection_Get-4       	| 30000   	| 48769 ns/op  	| 11960 B/op 	| 205 allocs/op 	|
| BenchmarkCollection_Has-4       	| 500000  	| 2734 ns/op   	| 280 B/op   	| 4 allocs/op   	|
| BenchmarkCollection_List-4      	| 100000  	| 16198 ns/op  	| 6440 B/op  	| 16 allocs/op  	|
| BenchmarkCollection_TotalItem-4 	| 100000  	| 16122 ns/op  	| 6440 B/op  	| 16 allocs/op  	|
| BenchmarkCollection_Remove-4    	| 1000000 	| 1703 ns/op   	| 432 B/op   	| 10 allocs/op  	|
| BenchmarkCollection_Flush-4     	| 2000000 	| 873 ns/op    	| 272 B/op   	| 3 allocs/op   	|
